### ISSUE TITLE
corn dough cant be made in cooking pot

### ISSUE THREAD

**Issue by grandphoenix663** [Nyancatpig/Cultural-Delights-1.19.2#14]
the recipe for corn dough for the cooking pot no longer exists. attempting to do the recipe yields no corn dough. the only avaliable recipe for it is one using a water bucket in a normal crafting grid
![gd](https://github.com/Nyancatpig/Cultural-Delights-1.19.2/assets/130688670/5a94d0c1-8133-4bb6-bfed-cba5ed12407f)

**Comment by Nyancatpig** [comment]
I removed that recipe, as well as the wheat dough in cooking pot recipe

**Comment by Aceplante2** [comment]
so are you supposed to tediously place in a new water bucket to craft 3 at a time? im glad i play 1.18 then

**Comment by Nyancatpig** [comment]
thats how farmer’s delight does it, i decided not to change that

also dough isnt made via cooking so the recipe made no sense
