### ISSUE TITLE
Cannot cut squid on a cutting board

### ISSUE THREAD

**Issue by Desoroxxx** [Nyancatpig/Cultural-Delights-1.19.2#20]
![image](https://github.com/Nyancatpig/Cultural-Delights-1.19.2/assets/82710983/aeaeef01-310a-4a37-8f04-c0b9bceec703)
![image](https://github.com/Nyancatpig/Cultural-Delights-1.19.2/assets/82710983/fa579a0e-16a3-42f6-bf2f-7c6b64f8e1d4)

**Comment by Nyancatpig** [comment]
One of the mods you are using must add a knife to the farmer's delight knives tag that doesn't exist.
