### ISSUE TITLE
Avocado blocks misbehaving

### ISSUE THREAD

**Issue by hammertater** [Nyancatpig/Cultural-Delights-1.19.2#3]
Hey, I noticed two issues with your avocado blocks in 1.19.2:

1 - fruiting_avocado_leaves are missing the minecraft:leaves tag

2 - when you make your logs strippable: https://github.com/Nyancatpig/Cultural-Delights-1.19.2/blob/fa9f10eae4fe652ebf2fc3221093b0c102768b36/src/main/java/com/ncpbails/culturaldelights/block/ModBlocks.java#L57
It's better to check for the correct tool action, like so:
```java
if (toolAction == ToolActions.AXE_STRIP)
```
Because not all axes will be instances of `AxeItem`, and some mods might try to strip logs without using any kind of axe

**Comment by Nyancatpig** [comment]
this should be fixed in the next update
